config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tickets#index'

  namespace :api do
    resources :tickets, only: [:create]
  end

  resources :tickets, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket

  validates :company_name, presence: true
  validates :address, presence: true
  validates :crew_on_site, presence: true
end

app/models/ticket.rb
# require 'rgeo'
# require 'rgeo/wkt_parser'

class Ticket < ApplicationRecord
  has_one :excavator
  validates :request_number, presence: true, uniqueness: true
  validates :sequence_number, presence: true
  validates :request_type, presence: true
  validates :request_action, presence: true
  validates :response_due_date_time, presence: true
  validates :primary_service_area_code, presence: true
  validates :additional_service_area_codes, presence: true
  validates :digsite_info_well_known_text, presence: true

  before_save :format_polygon, if: -> { digsite_info_well_known_text.present? }

  def format_polygon
    self.digsite_info_well_known_text = digsite_info_well_known_text.gsub(/\s+/, ' ').gsub(/\s*,\s*/, ',')
  end
end

app/controllers/api/tickets_controller.rb
module Api
  class TicketsController < ApplicationController
    class SaveFailure < StandardError; end

    skip_before_action :verify_authenticity_token
    before_action :check_address_data, only: :create

    def create
      attributes = ticket_data.slice('request_number', 'sequence_number', 'request_type', 'request_action')
      attributes.merge!(fill_ticket_data(ticket_data))

      Ticket.transaction do
        ticket = Ticket.new(attributes)

        raise SaveFailure, ticket.errors.full_messages.to_json unless ticket.save

        format_excavator_payload = ticket_data['excavator']
        excavator = initialize_excavator(format_excavator_payload, ticket)

        raise SaveFailure, excavator.errors.full_messages.to_json unless excavator.save

        render json: {
          status: 'success',
          ticket: TicketSerializer.new(ticket).as_json,
          excavator: ExcavatorSerializer.new(excavator).as_json
        }, status: :created

      end
    rescue SaveFailure => e
      render json: { errors: JSON.parse(e.message) }, status: :unprocessable_entity
    end

    private

    def check_address_data
      excavator_hash = ticket_data['excavator']

      errors = []
      errors << 'Address is required' if excavator_hash[:address].blank?
      errors << 'City key is required' if excavator_hash[:city].blank?
      errors << 'State key is required' if excavator_hash[:state].blank?
      errors << 'Zip key is required' if excavator_hash[:zip].blank?

      return if errors.empty?

      render json: { errors: errors }, status: :unprocessable_entity
    end

    def excavator_address_format(data)
      [data['address'], data['city'], data['state'], data['zip']].compact.join(', ')
    end

    def fill_ticket_data(data)
      {
        response_due_date_time: data.dig('date_times', 'response_due_date_time'),
        primary_service_area_code: data.dig('service_area', 'primary_service_area_code', 'sa_code'),
        additional_service_area_codes: data.dig('service_area', 'additional_service_area_codes', 'sa_code')&.join(', '),
        digsite_info_well_known_text: data.dig('excavation_info', 'digsite_info', 'well_known_text')
      }
    end

    def initialize_excavator(data, ticket)
      Excavator.new(
        ticket: ticket,
        company_name: data['company_name'],
        address: excavator_address_format(data),
        crew_on_site: data['crew_onsite']
      )
    end

    def ticket_data
      @ticket_data ||= ticket_params.to_h.deep_transform_keys!(&:underscore)
    end

    def ticket_params
      params.permit(
        :RequestNumber,
        :SequenceNumber,
        :RequestType,
        :RequestAction,
        DateTimes: :ResponseDueDateTime,
        ServiceArea: [
          PrimaryServiceAreaCode: :SACode,
          AdditionalServiceAreaCodes: { SACode: [] }
        ],
        ExcavationInfo: [ DigsiteInfo: :WellKnownText ],
        Excavator: %i[CompanyName Address City State Zip CrewOnsite]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include TicketsHelper

  def index
    @tickets = Ticket.order(:created_at).page(params[:page]).per(15)
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def crew_on_site_status(ticket)
    ticket.excavator.crew_on_site? ? 'Yes' : 'No'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeospatialApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tickets/index.html.erb
<div>
  <div class="text-4xl font-semibold mb-4">Tickets</div>

  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-50">
      <tr>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Request Number</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Sequence Number</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Request Type</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Request Action</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Due Date</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Primary Service Area Code</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Additional Service Area Code</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% @tickets.each do |ticket| %>
        <tr data-url="<%= ticket_path(ticket) %>">
          <td class="px-6 py-4"><%= ticket.request_number %></td>
          <td class="px-6 py-4"><%= ticket.sequence_number %></td>
          <td class="px-6 py-4"><%= ticket.request_type %></td>
          <td class="px-6 py-4"><%= ticket.request_action %></td>
          <td class="px-6 py-4"><%= ticket.response_due_date_time %></td>
          <td class="px-6 py-4"><%= ticket.primary_service_area_code %></td>
          <td class="px-6 py-4"><%= ticket.additional_service_area_codes %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="flex justify-end">
    <%= paginate @tickets %>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="text-4xl text-gray-700 px-2">Ticket <%= @ticket.request_number %></div>
<div class="bg-gray-50 m-5 p-8 rounded-lg">
  <div class="min-w-full px-6 py-4 mb-8">
    <div class="text-sm font-medium text-gray-500 uppercase">Request Number</div>
    <div><%= @ticket.request_number %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Sequence Number</div>
    <div><%= @ticket.sequence_number %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Request Type</div>
    <div><%= @ticket.request_type %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Request Action</div>
    <div><%= @ticket.request_action %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Due Date</div>
    <div><%= @ticket.response_due_date_time %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Primary Service Area Code</div>
    <div><%= @ticket.primary_service_area_code %></div>

    <div class="text-sm font-medium text-gray-500 uppercase">Additional Service Area Code</div>
    <div><%= @ticket.additional_service_area_codes %></div>
  </div>

  <div class="font-bold text-gray-700 px-6 py-4">Excavator Info</div>
  <div class="px-6 py-2">
    <%= @ticket.excavator.company_name %>
  </div>
  <div class="text-xs whitespace-nowrap px-6">
    <%= @ticket.excavator.address %>
  </div>
  <div class="text-xs whitespace-nowrap px-6">
    Crew On Site: <%= crew_on_site_status(@ticket) %>
  </div>
  <div id="map" style="height: 400px; width: 100%;" data-wkt-polygon="<%= @ticket.digsite_info_well_known_text %>"></div>
</div>

<%= link_to 'Back', tickets_path, class: "flex text-xl justify-end mt-4" %>

<script>
  window.GOOGLE_API_KEY = '<%= ENV['GOOGLE_API_KEY'] %>';
</script>